/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as IndexRouteImport } from './routes/index'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enrollment': typeof EnrollmentRoute
  '/monitoring': typeof MonitoringRoute
  '/verification': typeof VerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enrollment': typeof EnrollmentRoute
  '/monitoring': typeof MonitoringRoute
  '/verification': typeof VerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enrollment': typeof EnrollmentRoute
  '/monitoring': typeof MonitoringRoute
  '/verification': typeof VerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/enrollment' | '/monitoring' | '/verification'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/enrollment' | '/monitoring' | '/verification'
  id: '__root__' | '/' | '/enrollment' | '/monitoring' | '/verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnrollmentRoute: typeof EnrollmentRoute
  MonitoringRoute: typeof MonitoringRoute
  VerificationRoute: typeof VerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnrollmentRoute: EnrollmentRoute,
  MonitoringRoute: MonitoringRoute,
  VerificationRoute: VerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
